spring.application.name=multipledatabase
server.port=9097
# Primary database (e.g., MySQL)
spring.datasource.primary.url=jdbc:mysql://localhost/awfis
spring.datasource.primary.username=root
spring.datasource.primary.password=Sampath@2603
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.primary.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Secondary database (e.g.,mysql)
spring.datasource.secondary.url=jdbc:mysql://localhost/karthik
spring.datasource.secondary.username=root
spring.datasource.secondary.password=Sampath@2603
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.secondary.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cron.job.time=0 */1 * * * ?